#!/bin/bash
# Compile of the causal_product shared library.
# These lines were copy pasted from the build process of the full library:
# git clone https://github.com/idiap/fast-transformers
# cd fast-transformers
# python setup.py install
# 
# The problem is that the compile fails, and so even if I modify the cpp code i won't be able to use the code in python.
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/anthon@ad.cmm.se/projects/dataintegration/pyenv/lib/python3.10/site-packages/torch/include -I/home/anthon@ad.cmm.se/projects/dataintegration/pyenv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/anthon@ad.cmm.se/projects/dataintegration/pyenv/lib/python3.10/site-packages/torch/include/TH -I/home/anthon@ad.cmm.se/projects/dataintegration/pyenv/lib/python3.10/site-packages/torch/include/THC -I/home/anthon@ad.cmm.se/projects/dataintegration/pyenv/include -I/usr/include/python3.10 -c causal_product_cpu.cpp -o causal_product_cpu.o -fopenmp -ffast-math -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=causal_product_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
x86_64-linux-gnu-g++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 causal_product_cpu.o -L/home/anthon@ad.cmm.se/projects/dataintegration/pyenv/lib/python3.10/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o causal_product_cpu2.cpython-310-x86_64-linux-gnu.so